<a href="https://colab.research.google.com/github/yash-kumar-yks/song-recommendation/blob/main/training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras
from keras.layers import Activation, Dense, Dropout, Conv2D, \
                         Flatten, MaxPooling2D
from keras.models import Sequential
import numpy as np
import pandas as pd
import random

In [ ]:
# Read Data
data = pd.read_csv('music.csv')
data.loc[4353]

In [ ]:
!pwd

/content

In [ ]:
data = data.drop(["artist.id", "artist.name", "artist_mbtags","location", "song.id","latitude", "key", "longitude", "release.id","release.name","similar", "title", "year"], axis=1)

In [ ]:
data.shape

(10000, 22)

In [ ]:
data=data.drop(["terms_freq", "time_signature", "time_signature_confidence"], axis=1)
data=data.dropna()

In [ ]:
data.head()

    artist.hotttnesss  artist_mbtags_count  ...    tempo             terms
0            0.401998                  0.0  ...   92.198           hip hop
4            0.401724                  0.0  ...  129.738          pop punk
8            0.332276                  0.0  ...   86.643          new wave
10           0.296269                  0.0  ...  146.765  alternative rock
11           0.351556                  0.0  ...  117.975               ccm

[5 rows x 19 columns]

In [ ]:


data=pd.get_dummies(data, columns=['terms'])
data.shape
Y=data[data.columns[-402:]]

In [ ]:
Y.loc[4353]

terms_Russian Easter Festival_ Overture_ Op.36    0
terms_acid jazz                                   0
terms_afrobeat                                    0
terms_all-female                                  0
terms_alternative                                 0
                                                 ..
terms_world beat                                  0
terms_world fusion                                0
terms_zouk                                        0
terms_zouklove                                    0
terms_zydeco                                      0
Name: 4353, Length: 402, dtype: uint8

In [ ]:

X=data[data.columns[0:18]]
X

      artist.hotttnesss  artist_mbtags_count  ...  tatums_start    tempo
0              0.401998                  0.0  ...       0.28519   92.198
4              0.401724                  0.0  ...       0.13576  129.738
8              0.332276                  0.0  ...       1.22595   86.643
10             0.296269                  0.0  ...       0.11194  146.765
11             0.351556                  0.0  ...       0.17270  117.975
...                 ...                  ...  ...           ...      ...
9993           0.331535                  0.0  ...       0.05143  119.271
9995           0.499826                  1.0  ...       0.22262  140.185
9996           0.409779                  1.0  ...       0.07692   77.072
9998           0.216829                  0.0  ...       0.28192  137.663
9999           0.509243                  0.0  ...       0.20535  150.575

[5645 rows x 18 columns]

In [ ]:

from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.37135944, 0.        , 0.07261237, ..., 0.08442102, 0.02328874,
        0.35079215],
       [0.37110645, 0.        , 0.01976231, ..., 0.10837101, 0.01108622,
        0.49362321],
       [0.30695147, 0.        , 0.09101955, ..., 0.01311289, 0.10011163,
        0.32965666],
       ...,
       [0.37854783, 0.11111111, 0.01163153, ..., 0.06545609, 0.00628132,
        0.29324121],
       [0.20030335, 0.        , 0.0612067 , ..., 0.0456242 , 0.02302171,
        0.52377601],
       [0.47043131, 0.        , 0.00609808, ..., 0.07694342, 0.01676897,
        0.57290319]])

In [ ]:

from sklearn.model_selection import train_test_split

X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

In [ ]:
Y_train

      terms_Russian Easter Festival_ Overture_ Op.36  ...  terms_zydeco
2108                                               0  ...             0
5842                                               0  ...             0
1786                                               0  ...             0
6801                                               0  ...             0
1491                                               0  ...             0
...                                              ...  ...           ...
6766                                               0  ...             0
2837                                               0  ...             0
3189                                               0  ...             0
3125                                               0  ...             0
4353                                               0  ...             0

[3951 rows x 402 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
def create():
  model = Sequential([   Dense(64, activation='relu', input_shape=(18,)),   
                        Dense(256, activation='relu'),  
                        Dense(512, activation='relu'),  
                        Dense(402, activation='sigmoid')])
  model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
  return model

In [ ]:
model=create()

In [ ]:
model.fit(X_train, Y_train,          
                 batch_size=32, epochs=100,         
                 validation_data=(X_val, Y_val))

Epoch 1/100
124/124 [==============================] - 1s 8ms/step - loss: 5.5536 - accuracy: 0.0400 - val_loss: 5.4519 - val_accuracy: 0.0307
Epoch 2/100
124/124 [==============================] - 1s 6ms/step - loss: 5.3018 - accuracy: 0.0443 - val_loss: 5.3631 - val_accuracy: 0.0425
Epoch 3/100
124/124 [==============================] - 1s 6ms/step - loss: 5.1475 - accuracy: 0.0468 - val_loss: 5.2927 - val_accuracy: 0.0460
Epoch 4/100
124/124 [==============================] - 1s 6ms/step - loss: 5.0256 - accuracy: 0.0486 - val_loss: 5.2776 - val_accuracy: 0.0342
Epoch 5/100
124/124 [==============================] - 1s 6ms/step - loss: 4.9285 - accuracy: 0.0445 - val_loss: 5.2274 - val_accuracy: 0.0342
Epoch 6/100
124/124 [==============================] - 1s 6ms/step - loss: 4.8330 - accuracy: 0.0466 - val_loss: 5.2221 - val_accuracy: 0.0331
Epoch 7/100
124/124 [==============================] - 1s 6ms/step - loss: 4.7312 - accuracy: 0.0501 - val_loss: 5.2211 - val_accuracy: 0.0413
Epoch 8/100
124/124 [==============================] - 1s 6ms/step - loss: 4.6347 - accuracy: 0.0491 - val_loss: 5.2145 - val_accuracy: 0.0401
Epoch 9/100
124/124 [==============================] - 1s 6ms/step - loss: 4.5552 - accuracy: 0.0529 - val_loss: 5.3113 - val_accuracy: 0.0390
Epoch 10/100
124/124 [==============================] - 1s 6ms/step - loss: 4.4543 - accuracy: 0.0557 - val_loss: 5.3077 - val_accuracy: 0.0425
Epoch 11/100
124/124 [==============================] - 1s 6ms/step - loss: 4.3786 - accuracy: 0.0587 - val_loss: 5.3536 - val_accuracy: 0.0413
Epoch 12/100
124/124 [==============================] - 1s 6ms/step - loss: 4.2856 - accuracy: 0.0628 - val_loss: 5.4406 - val_accuracy: 0.0366
Epoch 13/100
124/124 [==============================] - 1s 6ms/step - loss: 4.2000 - accuracy: 0.0650 - val_loss: 5.5057 - val_accuracy: 0.0413
Epoch 14/100
124/124 [==============================] - 1s 6ms/step - loss: 4.1109 - accuracy: 0.0724 - val_loss: 5.5003 - val_accuracy: 0.0484
Epoch 15/100
124/124 [==============================] - 1s 6ms/step - loss: 4.0112 - accuracy: 0.0845 - val_loss: 5.6303 - val_accuracy: 0.0543
Epoch 16/100
124/124 [==============================] - 1s 6ms/step - loss: 3.9181 - accuracy: 0.0952 - val_loss: 5.6549 - val_accuracy: 0.0579
Epoch 17/100
124/124 [==============================] - 1s 7ms/step - loss: 3.8331 - accuracy: 0.1038 - val_loss: 5.7895 - val_accuracy: 0.0579
Epoch 18/100
124/124 [==============================] - 1s 7ms/step - loss: 3.7410 - accuracy: 0.1149 - val_loss: 5.9135 - val_accuracy: 0.0472
Epoch 19/100
124/124 [==============================] - 1s 6ms/step - loss: 3.6451 - accuracy: 0.1202 - val_loss: 6.0427 - val_accuracy: 0.0519
Epoch 20/100
124/124 [==============================] - 1s 6ms/step - loss: 3.5518 - accuracy: 0.1324 - val_loss: 6.1525 - val_accuracy: 0.0543
Epoch 21/100
124/124 [==============================] - 1s 6ms/step - loss: 3.4666 - accuracy: 0.1412 - val_loss: 6.1651 - val_accuracy: 0.0519
Epoch 22/100
124/124 [==============================] - 1s 6ms/step - loss: 3.3813 - accuracy: 0.1508 - val_loss: 6.3034 - val_accuracy: 0.0472
Epoch 23/100
124/124 [==============================] - 1s 7ms/step - loss: 3.2907 - accuracy: 0.1640 - val_loss: 6.4510 - val_accuracy: 0.0425
Epoch 24/100
124/124 [==============================] - 1s 6ms/step - loss: 3.1921 - accuracy: 0.1759 - val_loss: 6.5589 - val_accuracy: 0.0378
Epoch 25/100
124/124 [==============================] - 1s 7ms/step - loss: 3.1081 - accuracy: 0.1916 - val_loss: 6.6635 - val_accuracy: 0.0531
Epoch 26/100
124/124 [==============================] - 1s 6ms/step - loss: 3.0207 - accuracy: 0.2113 - val_loss: 6.7868 - val_accuracy: 0.0390
Epoch 27/100
124/124 [==============================] - 1s 6ms/step - loss: 2.9504 - accuracy: 0.2275 - val_loss: 6.8756 - val_accuracy: 0.0390
Epoch 28/100
124/124 [==============================] - 1s 7ms/step - loss: 2.8684 - accuracy: 0.2329 - val_loss: 6.9953 - val_accuracy: 0.0484
Epoch 29/100
124/124 [==============================] - 1s 6ms/step - loss: 2.7809 - accuracy: 0.2561 - val_loss: 7.0935 - val_accuracy: 0.0437
Epoch 30/100
124/124 [==============================] - 1s 7ms/step - loss: 2.7017 - accuracy: 0.2663 - val_loss: 7.1917 - val_accuracy: 0.0425
Epoch 31/100
124/124 [==============================] - 1s 7ms/step - loss: 2.6391 - accuracy: 0.2789 - val_loss: 7.2941 - val_accuracy: 0.0449
Epoch 32/100
124/124 [==============================] - 1s 7ms/step - loss: 2.5479 - accuracy: 0.3055 - val_loss: 7.4439 - val_accuracy: 0.0401
Epoch 33/100
124/124 [==============================] - 1s 6ms/step - loss: 2.4742 - accuracy: 0.3154 - val_loss: 7.5217 - val_accuracy: 0.0460
Epoch 34/100
124/124 [==============================] - 1s 6ms/step - loss: 2.4013 - accuracy: 0.3311 - val_loss: 7.6883 - val_accuracy: 0.0390
Epoch 35/100
124/124 [==============================] - 1s 6ms/step - loss: 2.3279 - accuracy: 0.3576 - val_loss: 7.7672 - val_accuracy: 0.0342
Epoch 36/100
124/124 [==============================] - 1s 6ms/step - loss: 2.2689 - accuracy: 0.3657 - val_loss: 7.8631 - val_accuracy: 0.0449
Epoch 37/100
124/124 [==============================] - 1s 7ms/step - loss: 2.1912 - accuracy: 0.3870 - val_loss: 7.9581 - val_accuracy: 0.0390
Epoch 38/100
124/124 [==============================] - 1s 7ms/step - loss: 2.1324 - accuracy: 0.4088 - val_loss: 8.0384 - val_accuracy: 0.0508
Epoch 39/100
124/124 [==============================] - 1s 6ms/step - loss: 2.0745 - accuracy: 0.4244 - val_loss: 8.1854 - val_accuracy: 0.0354
Epoch 40/100
124/124 [==============================] - 1s 6ms/step - loss: 2.0187 - accuracy: 0.4331 - val_loss: 8.2885 - val_accuracy: 0.0413
Epoch 41/100
124/124 [==============================] - 1s 7ms/step - loss: 1.9414 - accuracy: 0.4576 - val_loss: 8.3553 - val_accuracy: 0.0390
Epoch 42/100
124/124 [==============================] - 1s 7ms/step - loss: 1.8707 - accuracy: 0.4710 - val_loss: 8.4885 - val_accuracy: 0.0460
Epoch 43/100
124/124 [==============================] - 1s 7ms/step - loss: 1.8296 - accuracy: 0.4870 - val_loss: 8.6069 - val_accuracy: 0.0437
Epoch 44/100
124/124 [==============================] - 1s 7ms/step - loss: 1.7626 - accuracy: 0.4973 - val_loss: 8.7089 - val_accuracy: 0.0401
Epoch 45/100
124/124 [==============================] - 1s 7ms/step - loss: 1.7234 - accuracy: 0.5072 - val_loss: 8.7057 - val_accuracy: 0.0437
Epoch 46/100
124/124 [==============================] - 1s 7ms/step - loss: 1.6691 - accuracy: 0.5292 - val_loss: 8.8136 - val_accuracy: 0.0390
Epoch 47/100
124/124 [==============================] - 1s 6ms/step - loss: 1.6139 - accuracy: 0.5434 - val_loss: 8.8906 - val_accuracy: 0.0472
Epoch 48/100
124/124 [==============================] - 1s 6ms/step - loss: 1.5526 - accuracy: 0.5520 - val_loss: 8.9840 - val_accuracy: 0.0425
Epoch 49/100
124/124 [==============================] - 1s 6ms/step - loss: 1.5192 - accuracy: 0.5611 - val_loss: 9.0966 - val_accuracy: 0.0437
Epoch 50/100
124/124 [==============================] - 1s 7ms/step - loss: 1.4726 - accuracy: 0.5811 - val_loss: 9.1111 - val_accuracy: 0.0472
Epoch 51/100
124/124 [==============================] - 1s 6ms/step - loss: 1.4372 - accuracy: 0.5831 - val_loss: 9.2253 - val_accuracy: 0.0472
Epoch 52/100
124/124 [==============================] - 1s 7ms/step - loss: 1.4075 - accuracy: 0.5971 - val_loss: 9.2400 - val_accuracy: 0.0342
Epoch 53/100
124/124 [==============================] - 1s 6ms/step - loss: 1.3553 - accuracy: 0.6138 - val_loss: 9.3245 - val_accuracy: 0.0413
Epoch 54/100
124/124 [==============================] - 1s 7ms/step - loss: 1.2946 - accuracy: 0.6209 - val_loss: 9.3940 - val_accuracy: 0.0508
Epoch 55/100
124/124 [==============================] - 1s 7ms/step - loss: 1.2549 - accuracy: 0.6350 - val_loss: 9.4782 - val_accuracy: 0.0366
Epoch 56/100
124/124 [==============================] - 1s 7ms/step - loss: 1.2280 - accuracy: 0.6434 - val_loss: 9.5255 - val_accuracy: 0.0508
Epoch 57/100
124/124 [==============================] - 1s 7ms/step - loss: 1.2098 - accuracy: 0.6446 - val_loss: 9.5813 - val_accuracy: 0.0519
Epoch 58/100
124/124 [==============================] - 1s 7ms/step - loss: 1.1562 - accuracy: 0.6586 - val_loss: 9.6595 - val_accuracy: 0.0401
Epoch 59/100
124/124 [==============================] - 1s 6ms/step - loss: 1.1197 - accuracy: 0.6674 - val_loss: 9.7430 - val_accuracy: 0.0401
Epoch 60/100
124/124 [==============================] - 1s 7ms/step - loss: 1.0812 - accuracy: 0.6813 - val_loss: 9.7442 - val_accuracy: 0.0472
Epoch 61/100
124/124 [==============================] - 1s 7ms/step - loss: 1.0595 - accuracy: 0.6844 - val_loss: 9.8026 - val_accuracy: 0.0567
Epoch 62/100
124/124 [==============================] - 1s 7ms/step - loss: 1.0176 - accuracy: 0.7059 - val_loss: 9.8524 - val_accuracy: 0.0437
Epoch 63/100
124/124 [==============================] - 1s 7ms/step - loss: 1.0070 - accuracy: 0.6986 - val_loss: 9.9767 - val_accuracy: 0.0460
Epoch 64/100
124/124 [==============================] - 1s 6ms/step - loss: 0.9763 - accuracy: 0.7175 - val_loss: 10.0580 - val_accuracy: 0.0437
Epoch 65/100
124/124 [==============================] - 1s 6ms/step - loss: 0.9517 - accuracy: 0.7208 - val_loss: 10.0595 - val_accuracy: 0.0519
Epoch 66/100
124/124 [==============================] - 1s 6ms/step - loss: 0.9211 - accuracy: 0.7282 - val_loss: 10.1142 - val_accuracy: 0.0425
Epoch 67/100
124/124 [==============================] - 1s 6ms/step - loss: 0.8820 - accuracy: 0.7345 - val_loss: 10.1639 - val_accuracy: 0.0425
Epoch 68/100
124/124 [==============================] - 1s 6ms/step - loss: 0.8780 - accuracy: 0.7401 - val_loss: 10.2937 - val_accuracy: 0.0449
Epoch 69/100
124/124 [==============================] - 1s 6ms/step - loss: 0.8391 - accuracy: 0.7547 - val_loss: 10.2792 - val_accuracy: 0.0401
Epoch 70/100
124/124 [==============================] - 1s 7ms/step - loss: 0.8171 - accuracy: 0.7535 - val_loss: 10.3059 - val_accuracy: 0.0460
Epoch 71/100
124/124 [==============================] - 1s 7ms/step - loss: 0.8015 - accuracy: 0.7611 - val_loss: 10.4283 - val_accuracy: 0.0472
Epoch 72/100
124/124 [==============================] - 1s 8ms/step - loss: 0.7751 - accuracy: 0.7656 - val_loss: 10.4404 - val_accuracy: 0.0484
Epoch 73/100
124/124 [==============================] - 1s 8ms/step - loss: 0.7466 - accuracy: 0.7826 - val_loss: 10.4795 - val_accuracy: 0.0508
Epoch 74/100
124/124 [==============================] - 1s 7ms/step - loss: 0.7258 - accuracy: 0.7846 - val_loss: 10.4801 - val_accuracy: 0.0531
Epoch 75/100
124/124 [==============================] - 1s 8ms/step - loss: 0.6931 - accuracy: 0.7957 - val_loss: 10.5685 - val_accuracy: 0.0567
Epoch 76/100
124/124 [==============================] - 1s 7ms/step - loss: 0.6756 - accuracy: 0.7968 - val_loss: 10.6909 - val_accuracy: 0.0437
Epoch 77/100
124/124 [==============================] - 1s 8ms/step - loss: 0.6702 - accuracy: 0.7998 - val_loss: 10.6636 - val_accuracy: 0.0543
Epoch 78/100
124/124 [==============================] - 1s 7ms/step - loss: 0.6476 - accuracy: 0.8026 - val_loss: 10.8070 - val_accuracy: 0.0496
Epoch 79/100
124/124 [==============================] - 1s 7ms/step - loss: 0.6669 - accuracy: 0.7932 - val_loss: 10.7408 - val_accuracy: 0.0496
Epoch 80/100
124/124 [==============================] - 1s 7ms/step - loss: 0.6054 - accuracy: 0.8104 - val_loss: 10.7909 - val_accuracy: 0.0519
Epoch 81/100
124/124 [==============================] - 1s 7ms/step - loss: 0.5900 - accuracy: 0.8203 - val_loss: 10.8558 - val_accuracy: 0.0543
Epoch 82/100
124/124 [==============================] - 1s 7ms/step - loss: 0.5847 - accuracy: 0.8231 - val_loss: 10.8615 - val_accuracy: 0.0531
Epoch 83/100
124/124 [==============================] - 1s 7ms/step - loss: 0.5737 - accuracy: 0.8289 - val_loss: 10.8964 - val_accuracy: 0.0460
Epoch 84/100
124/124 [==============================] - 1s 7ms/step - loss: 0.5491 - accuracy: 0.8317 - val_loss: 10.9768 - val_accuracy: 0.0543
Epoch 85/100
124/124 [==============================] - 1s 7ms/step - loss: 0.5198 - accuracy: 0.8438 - val_loss: 11.0743 - val_accuracy: 0.0472
Epoch 86/100
124/124 [==============================] - 1s 6ms/step - loss: 0.5409 - accuracy: 0.8322 - val_loss: 11.0801 - val_accuracy: 0.0449
Epoch 87/100
124/124 [==============================] - 1s 7ms/step - loss: 0.5051 - accuracy: 0.8540 - val_loss: 11.1120 - val_accuracy: 0.0437
Epoch 88/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4719 - accuracy: 0.8621 - val_loss: 11.0966 - val_accuracy: 0.0543
Epoch 89/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4602 - accuracy: 0.8555 - val_loss: 11.1606 - val_accuracy: 0.0531
Epoch 90/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4713 - accuracy: 0.8565 - val_loss: 11.2110 - val_accuracy: 0.0519
Epoch 91/100
124/124 [==============================] - 1s 6ms/step - loss: 0.4583 - accuracy: 0.8616 - val_loss: 11.3071 - val_accuracy: 0.0496
Epoch 92/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4686 - accuracy: 0.8600 - val_loss: 11.2654 - val_accuracy: 0.0460
Epoch 93/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4528 - accuracy: 0.8686 - val_loss: 11.3502 - val_accuracy: 0.0567
Epoch 94/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4812 - accuracy: 0.8560 - val_loss: 11.3907 - val_accuracy: 0.0460
Epoch 95/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4268 - accuracy: 0.8760 - val_loss: 11.4385 - val_accuracy: 0.0496
Epoch 96/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4052 - accuracy: 0.8818 - val_loss: 11.4194 - val_accuracy: 0.0449
Epoch 97/100
124/124 [==============================] - 1s 7ms/step - loss: 0.4179 - accuracy: 0.8767 - val_loss: 11.4059 - val_accuracy: 0.0508
Epoch 98/100
124/124 [==============================] - 1s 7ms/step - loss: 0.3827 - accuracy: 0.8866 - val_loss: 11.4623 - val_accuracy: 0.0496
Epoch 99/100
124/124 [==============================] - 1s 7ms/step - loss: 0.3667 - accuracy: 0.8960 - val_loss: 11.5363 - val_accuracy: 0.0496
Epoch 100/100
124/124 [==============================] - 1s 7ms/step - loss: 0.3397 - accuracy: 0.9056 - val_loss: 11.6510 - val_accuracy: 0.0366